# Generated by Django 4.2.7 on 2026-03-11 18:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='meta_gordura',
            field=models.DecimalField(blank=True, decimal_places=2, help_text='Meta de percentual de gordura (opcional)', max_digits=5, null=True),
        ),
        migrations.AddField(
            model_name='user',
            name='meta_peso',
            field=models.DecimalField(blank=True, decimal_places=2, help_text='Meta de peso em kg (opcional)', max_digits=5, null=True),
        ),
    ]
