# Generated by Django 4.2.7 on 2026-03-11 14:38

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Measurement',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('data_hora', models.DateTimeField(default=django.utils.timezone.now)),
                ('peso', models.DecimalField(decimal_places=2, help_text='Peso em kg', max_digits=5)),
                ('imc', models.DecimalField(decimal_places=2, help_text='Índice de Massa Corporal', max_digits=4)),
                ('percentual_gordura', models.DecimalField(decimal_places=2, help_text='Percentual de gordura (%)', max_digits=5)),
                ('percentual_massa_muscular', models.DecimalField(decimal_places=2, help_text='Percentual de massa muscular (%)', max_digits=5)),
                ('metabolismo_basal', models.IntegerField(help_text='Metabolismo basal em kcal')),
                ('idade_metabolica', models.IntegerField(help_text='Idade metabólica em anos')),
                ('indice_gordura_visceral', models.DecimalField(decimal_places=1, help_text='Índice de gordura visceral', max_digits=4)),
                ('usuario', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='medicoes', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Medição de Bioimpedância',
                'verbose_name_plural': 'Medições de Bioimpedância',
                'ordering': ['-data_hora'],
            },
        ),
    ]
