# Generated by Django 4.2.7 on 2026-03-11 18:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('measurements', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='measurement',
            name='foto_costas',
            field=models.ImageField(blank=True, help_text='Foto de costas', null=True, upload_to='fotos/%Y/%m/'),
        ),
        migrations.AddField(
            model_name='measurement',
            name='foto_frente',
            field=models.ImageField(blank=True, help_text='Foto de frente', null=True, upload_to='fotos/%Y/%m/'),
        ),
        migrations.AddField(
            model_name='measurement',
            name='foto_perfil',
            field=models.ImageField(blank=True, help_text='Foto de perfil', null=True, upload_to='fotos/%Y/%m/'),
        ),
        migrations.AddField(
            model_name='measurement',
            name='notas',
            field=models.TextField(blank=True, help_text='Notas adicionais sobre a medição', null=True),
        ),
    ]
